update localized_texts set RU = 'Ты назвала меня ''слабым''?!' where TOKEN = 'VELARC1SCENE2_SQUIRE_012';
update localized_texts set RU = 'П-прими это в следующий раз, когда тебе станет плохо... Это хорошее средство для слабого желудка...' where TOKEN = 'VELARC1SCENE2_VEL_007';
update localized_texts set RU = 'И почему, черт возьми, все хотят видеть, как я ее избиваю?!' where TOKEN = 'VELARC1SCENE1_SQUIRE_048';
update localized_texts set RU = 'В этом поединке определится, кто на самом деле "молокосос"!' where TOKEN = 'VELARC1SCENE1_JCOX_015';
update localized_texts set RU = 'Итак, поприветствуйте... в одном углу, всеми любимый завсегдатай таверны — Вэл Шарфе!' where TOKEN = 'VELARC1SCENE1_JCOX_012';
update localized_texts set RU = 'Конечно! Толпе это нравится, это приносит мне деньги, все счастливы!' where TOKEN = 'VELARC1SCENE1_JCOX_011';
update localized_texts set RU = 'Сегодня вас ждет потрясающий матч — старая добрая игра в армрестлинг!' where TOKEN = 'VELARC1SCENE1_JCOX_010';
update localized_texts set RU = 'Ладно! Послушайте, пьяные чурбаны!' where TOKEN = 'VELARC1SCENE1_JCOX_009';
update localized_texts set RU = 'Просто выслушай меня, ты, коротышка!' where TOKEN = 'VELARC1SCENE1_SQUIRE_018';
update localized_texts set RU = 'Давай, нападай! Покажем всем, кто из нас двоих маленькая девочка.' where TOKEN = 'VELARC1SCENE1_VEL_016';
update localized_texts set RU = 'Оно нужно этому {i}''кретину!''{/i}' where TOKEN = 'VELARC1SCENE1_VEL_011';
update localized_texts set RU = 'Босс! Подайте молочко! Этому... эм... кретину! Да, именно так…' where TOKEN = 'VELARC1SCENE1_VEL_010';
update localized_texts set RU = 'Ты пролил мою выпивку, ты... ты... ты слепой говнюк!' where TOKEN = 'VELARC1SCENE1_VEL_005';
update localized_texts set RU = 'Что? Меня? Побьют? Не может быть! Эта маленькая креветка? Пффф.' where TOKEN = 'VELARC1SCENE1_SQUIRE_049';
update localized_texts set RU = 'Эй, креветка! Я знаю, как мы можем уладить это, не калеча твое милое личико!' where TOKEN = 'VELARC1SCENE1_SQUIRE_017';
update localized_texts set RU = 'Черта с два я стану драться с креветкой!' where TOKEN = 'VELARC1SCENE1_CHOICE_002';

update localized_texts set RU = 'Но эй, благодаря всему этому я — один из лучших торговцев в округе. Здесь родилась, здесь же и выросла!' where TOKEN = 'AMYTOPICWORK_AMELIE_006';

update localized_texts set RU = '...Ах, какой денек! Настало "время для Паму"!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_001';
update localized_texts set RU = 'Это... Паму?' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_001';
update localized_texts set RU = 'Что она здесь делает в такое время? Пойду посмотрю....' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_002';
update localized_texts set RU = 'Эй-эй!' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_003';
update localized_texts set RU = 'Эээ... Думаю, мне не стоит здесь находиться....' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_004';
update localized_texts set RU = '...Может, я еще не участвую в той голубиной игре, но по крайней мере эта намного лучше, чем {i}Crush Crush!{/i}' where TOKEN = 'PAMUSPECIALSCENE_PAMU_002';
update localized_texts set RU = 'Я имею в виду, просто посмотрите на мои груди! У Паму наконец-то все в жизни получается!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_003';
update localized_texts set RU = 'Голуби?  {i}Crush... Crush?{/i} О чем она говорит?' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_005';
update localized_texts set RU = 'Ладно, неважно. Мне лучше уйти. Я не хочу создавать...' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_006';
update localized_texts set RU = '…!' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_007';
update localized_texts set RU = 'Гаааа!' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_001';
update localized_texts set RU = '...шумиху.' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_008';
update localized_texts set RU = 'Черт.' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_009';
update localized_texts set RU = 'Эй! Кто там? Отвечайте!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_004';
update localized_texts set RU = 'Эээ... Привет, Паму! Хорошая ночка, да?' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_002';
update localized_texts set RU = '…?!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_005';
update localized_texts set RU = 'Слушайте, извините! Я не хотел...' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_003';
update localized_texts set RU = 'Ох, это всего лишь ты! Какая досада.' where TOKEN = 'PAMUSPECIALSCENE_PAMU_006';
update localized_texts set RU = 'Ха! Я должна была этого ожидать. Я имею в виду, ТЫ ведь главный герой!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_007';
update localized_texts set RU = 'Ты должен увидеть нас всех голыми, видимо...' where TOKEN = 'PAMUSPECIALSCENE_PAMU_008';
update localized_texts set RU = 'Я... Еще раз, кто я?' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_004';
update localized_texts set RU = 'Ох, ничего! Не волнуйся об этом своей девственной головкой!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_009';
update localized_texts set RU = 'В-Вы можете перестать так меня называть?!' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_005';
update localized_texts set RU = 'Оу! Не хочу быть банальной, но… ты очень мил, когда злишься.' where TOKEN = 'PAMUSPECIALSCENE_PAMU_010';
update localized_texts set RU = 'Но, увы и ах. Трагично, правда. Дальше нам не по пути…' where TOKEN = 'PAMUSPECIALSCENE_PAMU_011';
update localized_texts set RU = 'Чертовски жаль. Я, наверное, была бы лучшей девушкой, если бы они дали мне… собственный "рут"! Настоящий материал для "вайфу"!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_012';
update localized_texts set RU = 'Собственный... Что? В этом нет никакого смысла, леди!' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_006';
update localized_texts set RU = 'Да, наверное, я должна прекратить это и снова стать Мисс Великий Архивариус, верно?' where TOKEN = 'PAMUSPECIALSCENE_PAMU_013';
update localized_texts set RU = 'Ну и хорошо! {$mcName}, ты хочешь найти в этом смысл?' where TOKEN = 'PAMUSPECIALSCENE_PAMU_014';
update localized_texts set RU = 'Да! Пожалуйста!' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_007';
update localized_texts set RU = 'Тогда повторяй за мной эти абсолютно оригинальные магические слова…' where TOKEN = 'PAMUSPECIALSCENE_PAMU_015';
update localized_texts set RU = 'Вабба-Лабба-Даб-Даб!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_016';
update localized_texts set RU = 'Хм… Звучит глупо.' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_008';
update localized_texts set RU = 'Просто повторяй!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_017';
update localized_texts set RU = 'Х-Хорошо... Вабба-Лабба…' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_009';
update localized_texts set RU = 'Вперед, волшебная палочка!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_018';
update localized_texts set RU = '{i}Хиаг!{/i}' where TOKEN = 'PAMUSPECIALSCENE_PAMU_019';
update localized_texts set RU = 'Эй, нет! Не кидайте это...' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_010';
update localized_texts set RU = 'Пффф!!' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_011';
update localized_texts set RU = 'Охх… моя… голова…' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_012';
update localized_texts set RU = 'Спокойной ночи, милый принц!' where TOKEN = 'PAMUSPECIALSCENE_PAMU_020';
update localized_texts set RU = 'Аааа…' where TOKEN = 'PAMUSPECIALSCENE_SQUIRE_013';
update localized_texts set RU = '… Что?' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_010';
update localized_texts set RU = 'Охх! Моя… Моя голова, как больно…' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_011';
update localized_texts set RU = 'Что это, черт возьми, было?' where TOKEN = 'PAMUSPECIALSCENE_NARRATION_012';

update localized_texts set RU = 'Хью говорил, что ему не нужен тупой оруженосец. Какие книги сделают меня умнее?' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_001';
update localized_texts set RU = 'Давай посмотрим... {i}'Брачные привычки монстров, Том первый?'{/i}' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_002';
update localized_texts set RU = 'Похоже, кому-то стало скучно...' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_003';
update localized_texts set RU = 'Давай начнем с этого!' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_004';
update localized_texts set RU = '{i}'Самец слизня отвлекает самку пищей. Пока она ест, мужчина пытается спариться с ней.'{/i}' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_005';
update localized_texts set RU = 'Фе, как отвратительно...' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_006';
update localized_texts set RU = '{i}'Если у самки закончится еда до того, как он закончит, она яростно оттолкнет его.'{/i}' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_007';
update localized_texts set RU = 'Пффф! Похоже на любовную жизнь Хью...' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_008';
update localized_texts set RU = 'Но на сегодня достаточно странных фактов о монстрах!' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_009';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_001';
update localized_texts set RU = 'Это случайно не Жизель? Что она делает со всеми этими книгами?' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_010';
update localized_texts set RU = 'Ах. Ох, нет…' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_002';
update localized_texts set RU = 'Эй, медсестра! Жизель! Что делаешь?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_001';
update localized_texts set RU = 'Иип!' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_003';
update localized_texts set RU = 'Ее книги упали. Похоже, я напугал ее....' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_011';
update localized_texts set RU = 'Хороший ход, {$mcName}!' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_012';
update localized_texts set RU = 'Нет... Нет...' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_004';
update localized_texts set RU = 'Извини за это. Я просто хотел помочь.' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_002';
update localized_texts set RU = '...!' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_005';
update localized_texts set RU = 'Она делает шаг назад и начинает ерзать.' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_013';
update localized_texts set RU = 'Ты в порядке?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_003';
update localized_texts set RU = 'Еще несколько вдохов, и она успокаивается.' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_014';
update localized_texts set RU = 'Э-это ты.' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_006';
update localized_texts set RU = 'Давай я помогу тебе...' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_004';
update localized_texts set RU = '{i}Искусство алхимии{/i}, {i}Руководство по оккультизму{/i}...' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_015';
update localized_texts set RU = 'Ух... Жизель?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_005';
update localized_texts set RU = 'Д-Да?' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_007';
update localized_texts set RU = 'Ты что... {i}ведьма{/i}?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_006';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_008';
update localized_texts set RU = 'Дурак.' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_009';
update localized_texts set RU = 'Я... Я не против! Я просто хочу убедиться…' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_007';
update localized_texts set RU = 'Так! Кто, черт возьми, шумит в моем архиве?!' where TOKEN = 'GISELLEARC1SCENE1_PAMU_001';
update localized_texts set RU = 'Жизель? Не могу поверить! Ты же лучше понимаешь, девочка!' where TOKEN = 'GISELLEARC1SCENE1_PAMU_002';
update localized_texts set RU = 'Н-Нет! Это его вина!' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_010';
update localized_texts set RU = 'Мне все равно, чья это вина. Дайте мне свои пропуска. Никаких книг в течение месяца. Вы  наказаны!' where TOKEN = 'GISELLEARC1SCENE1_PAMU_003';
update localized_texts set RU = 'Н-Нет, пожалуйста!' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_011';
update localized_texts set RU = 'Мои... Мои исследования.' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_012';
update localized_texts set RU = 'Прости, Жизель. Я не могу выделять любимчиков, какой бы милашкой ты не была…' where TOKEN = 'GISELLEARC1SCENE1_PAMU_004';
update localized_texts set RU = 'Слушайте, это не слишком?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_008';
update localized_texts set RU = 'Я здесь самый шумный, понимаете? Если кто-то виновен, так это я!' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_009';
update localized_texts set RU = 'Оооо! Посмотрите на него! Играешь в героя? Как мило!' where TOKEN = 'GISELLEARC1SCENE1_PAMU_005';
update localized_texts set RU = 'Пожалуйста?' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_013';
update localized_texts set RU = 'О, Жизель... Не делай такое лицо!' where TOKEN = 'GISELLEARC1SCENE1_PAMU_006';
update localized_texts set RU = '…' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_014';
update localized_texts set RU = 'Тьфу ты... хорошо! Поскольку это ваше первое нарушение, я отпущу вас обоих с предупреждением. Мое сердце не каменное!' where TOKEN = 'GISELLEARC1SCENE1_PAMU_007';
update localized_texts set RU = 'Просто не забывай играть тише... иначе.' where TOKEN = 'GISELLEARC1SCENE1_PAMU_008';
update localized_texts set RU = 'Извините…' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_015';
update localized_texts set RU = 'Эй, мне тоже жаль. Это больше не повторится!' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_010';
update localized_texts set RU = 'Хорошо, хорошо. Как скажешь. Просто успокойся. У меня здесь приличное заведение.' where TOKEN = 'GISELLEARC1SCENE1_PAMU_009';
update localized_texts set RU = 'Ох... это Паму!' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_016';
update localized_texts set RU = 'Фух! Было близко, да?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_014';
update localized_texts set RU = '...!' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_022';
update localized_texts set RU = 'Знаю, знаю... Я буду осторожнее.' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_015';
update localized_texts set RU = 'Итак... исследования, да? Над какой магией ты работаешь?' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_016';
update localized_texts set RU = 'Хмм..!' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_023';
update localized_texts set RU = 'Пока.' where TOKEN = 'GISELLEARC1SCENE1_GISELLE_024';
update localized_texts set RU = 'Эй, подожди!' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_017';
update localized_texts set RU = 'Я знал! Ты ведьма, не так ли?!' where TOKEN = 'GISELLEARC1SCENE1_SQUIRE_018';
update localized_texts set RU = 'Думаю, некоторым дамам нужно хранить свои секреты.…' where TOKEN = 'GISELLEARC1SCENE1_NARRATION_017';
update localized_texts set RU = 'Эй, Хью, где ты?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_001';
update localized_texts set RU = 'Я готов научится убивать людей!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_002';
update localized_texts set RU = 'Ооо, он оставил записку...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_001';
update localized_texts set RU = '{i}\'Оруженосец, попрактикуй выпады...\'{/i}' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_002';
update localized_texts set RU = '{i}\'Скоро вернусь. Хью ♥\' {/i}' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_003';
update localized_texts set RU = 'Серьезно... сердечко?' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_004';
update localized_texts set RU = 'Он думает, это мило? Неудивительно, что у него никогда не было секса. Жуть...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_005';
update localized_texts set RU = 'Привет! Привет!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_003';
update localized_texts set RU = 'Чего? Ты назвал меня глупцом?!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_004';
update localized_texts set RU = 'Ну, тогда лови, болван!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_005';
update localized_texts set RU = 'Ого! Спокойно, Оруженосец...' where TOKEN = 'GISELLEARC1SCENE2_HUGH_001';
update localized_texts set RU = 'Не спорь с соломенным чучелом!' where TOKEN = 'GISELLEARC1SCENE2_HUGH_002';
update localized_texts set RU = 'О, ты вернулся! Я почти закончил с этими выпадами.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_006';
update localized_texts set RU = 'Отлично, у меня для тебя хорошие новости!' where TOKEN = 'GISELLEARC1SCENE2_HUGH_003';
update localized_texts set RU = 'Я записал тебя в волонтеры!' where TOKEN = 'GISELLEARC1SCENE2_HUGH_004';
update localized_texts set RU = '...Хью, ты же знаешь, что такое волонтерство, верно?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_007';
update localized_texts set RU = 'Да. Это значит превратить такого человека, как ты в продуктивного члена общества.' where TOKEN = 'GISELLEARC1SCENE2_HUGH_005';
update localized_texts set RU = 'Эй, я могу нести свою ношу!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_008';
update localized_texts set RU = 'Ну, это не то, о чем говорила Эми.' where TOKEN = 'GISELLEARC1SCENE2_HUGH_006';
update localized_texts set RU = 'Уже…. Неважно... что теперь меня ждет?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_009';
update localized_texts set RU = 'Лазарету требуется пара рук.' where TOKEN = 'GISELLEARC1SCENE2_HUGH_007';
update localized_texts set RU = 'Надеюсь, не драить полы?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_010';
update localized_texts set RU = 'Скоро ты узнаешь...' where TOKEN = 'GISELLEARC1SCENE2_HUGH_008';
update localized_texts set RU = 'Да ладно тебе! ' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_011';
update localized_texts set RU = 'Что бы это ни было, тебе этого не избежать.' where TOKEN = 'GISELLEARC1SCENE2_HUGH_009';
update localized_texts set RU = 'Кроме того, благодаря этим случайным бодработкам я и прославился!' where TOKEN = 'GISELLEARC1SCENE2_HUGH_010';
update localized_texts set RU = 'Да, Хью... Поэтому все о тебе {i}безусловно{/i} очень высокого мнения.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_012';
update localized_texts set RU = 'Если у тебя есть время для оскорблений, то тем более есть время для работы!' where TOKEN = 'GISELLEARC1SCENE2_HUGH_011';
update localized_texts set RU = 'А теперь, за дело, Оруженосец!' where TOKEN = 'GISELLEARC1SCENE2_HUGH_012';
update localized_texts set RU = 'Вау! Почему так внезапно ты стал серьезен?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_013';
update localized_texts set RU = 'Что случилось с забавным, рисующим сердечки Хью?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_014';
update localized_texts set RU = 'Иди. Работа не ждет, {$mcName}.' where TOKEN = 'GISELLEARC1SCENE2_HUGH_013';
update localized_texts set RU = 'Хорошо, хорошо. Я пошел....' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_015';
update localized_texts set RU = 'Да сто пудов, полы драить…' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_006';
update localized_texts set RU = 'Эй, здесь есть кто-нибудь?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_016';
update localized_texts set RU = 'Я вызвался добровольцем в лазарет.... вроде того.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_017';
update localized_texts set RU = 'Минутку!' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_001';
update localized_texts set RU = 'О. Привет, док!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_018';
update localized_texts set RU = 'Это доктор Сесилия. Я раньше сталкивался с ней пару раз. Обычно она помогает нам, когда Эми заболевает.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_007';
update localized_texts set RU = 'Ооо, {$mcName}! Думаю, я правильно поняла, ты теперь оруженосец.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_002';
update localized_texts set RU = 'Это хорошая новость для нас.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_003';
update localized_texts set RU = 'Спасибо, док! С этого момента я буду под вашей опекой.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_019';
update localized_texts set RU = 'Так ты тот парень, которого Хью обещал? Какой способный мальчик.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_004';
update localized_texts set RU = 'Жизель, не могла бы ты подойти сюда на секунду?' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_005';
update localized_texts set RU = 'Медсестра? Возможно, это мой шанс произвести впечатление!' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_008';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_001';
update localized_texts set RU = 'О, нет…' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_002';
update localized_texts set RU = 'Эй, Жизель!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_020';
update localized_texts set RU = 'Пожалуйста, еще один доброволец.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_003';
update localized_texts set RU = 'Вы знаете друг друга?' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_006';
update localized_texts set RU = 'Нет.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_004';
update localized_texts set RU = 'Эй! Ты все еще злишься из-за той штуки в архиве?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_021';
update localized_texts set RU = 'Ну, не волнуйся, Жизель! Я компенсирую это сегодня!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_022';
update localized_texts set RU = 'Сомневаюсь.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_005';
update localized_texts set RU = 'Жизель, ты же знаешь, что мы не можем позволить себе выбирать помощников.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_007';
update localized_texts set RU = 'Я бы пошла с тобой, но я буду занята, ухаживая за Королем.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_008';
update localized_texts set RU = 'Хорошо.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_006';
update localized_texts set RU = 'Уверена, ты справишься, дорогая. Только не заходи слишком глубоко в лес.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_009';
update localized_texts set RU = 'Лес? Зачем нам лес?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_023';
update localized_texts set RU = 'Ты будешь присматривать за ней, пока она собирает травы.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_010';
update localized_texts set RU = 'Слава Богу! Я думал, что буду убирать листву.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_024';
update localized_texts set RU = 'Следить за кем-то не так уж сложно.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_025';
update localized_texts set RU = 'Да, берегись бандитов или диких кабанов...' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_011';
update localized_texts set RU = 'По какой-то причине, эти две вещи всегда ускользают от патруля.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_012';
update localized_texts set RU = 'Не волнуйся, я знаю, что делать!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_026';
update localized_texts set RU = 'Например?' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_013';
update localized_texts set RU = 'Бежать, конечно же!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_027';
update localized_texts set RU = 'Хорошо. Только не забудь про Жизель.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_014';
update localized_texts set RU = 'Конечно, не забуду!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_028';
update localized_texts set RU = 'Я готова.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_007';
update localized_texts set RU = 'Ну ладно. Вы двое, берегите себя.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_015';
update localized_texts set RU = 'Увидимся позже. Надеюсь, здоровыми и невредимыми.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_016';
update localized_texts set RU = 'Не волнуйтесь, мэм! Она в надежных руках!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_029';
update localized_texts set RU = 'Жизель, пошли....' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_030';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_008';
update localized_texts set RU = '... вперед.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_031';
update localized_texts set RU = 'Не принимай это на свой счет, {$mcName}. Она всегда была такой.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_017';
update localized_texts set RU = 'Я постараюсь.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_032';
update localized_texts set RU = 'Знаешь, присматривать за тобой было бы намного проще, если бы ты не убегала так далеко.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_033';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_009';
update localized_texts set RU = 'Это мое дыхание?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_034';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_010';
update localized_texts set RU = 'Я случайно не воняю? Я помню, как принимал ванну этим утром.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_035';
update localized_texts set RU = 'Я рада за тебя.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_011';
update localized_texts set RU = 'Я такой страшный?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_036';
update localized_texts set RU = 'Да.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_012';
update localized_texts set RU = 'Ну, по крайней мере, это лицо может отпугнуть кабанов, верно?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_037';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_013';
update localized_texts set RU = 'Крутой склон.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_009';
update localized_texts set RU = 'Жизель точно знает дорогу, да? Наверное, она часто ходит в лес...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_010';
update localized_texts set RU = 'Ну, я ничего не имею против. Здесь мило...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_011';
update localized_texts set RU = 'Если бы мне нравилось ходить пешком, я бы тоже, наверное, наслаждался пейзажем.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_012';
update localized_texts set RU = 'Жаль, что передо мной уже есть вариант получше....' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_013';
update localized_texts set RU = 'Так... тебе нужна моя помощь?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_038';
update localized_texts set RU = 'Нет.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_014';
update localized_texts set RU = 'Ничего страшного....' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_039';
update localized_texts set RU = 'Просто продолжай, не торопись.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_040';
update localized_texts set RU = 'Кажется, мне нравятся медсёстры…' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_014';
update localized_texts set RU = 'А... как называется это растение?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_041';
update localized_texts set RU = 'Агримония.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_015';
update localized_texts set RU = 'Тебе нужно быть осторожной с ним?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_042';
update localized_texts set RU = 'Да.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_016';
update localized_texts set RU = 'Тогда не спеши.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_043';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_017';
update localized_texts set RU = 'Готово.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_018';
update localized_texts set RU = 'Уже?!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_044';
update localized_texts set RU = 'Да. А что?' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_019';
update localized_texts set RU = 'Ох, ничего, правда.... Похоже, ты хорошо знаешь это место.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_045';
update localized_texts set RU = 'Ты даже знаешь, где найти травы!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_046';
update localized_texts set RU = 'Конечно.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_020';
update localized_texts set RU = 'Я так и знал! Ты ведьма!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_047';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_021';
update localized_texts set RU = 'Я шучу! Просто не думал, что ты любишь проводить время на природе, вот и все.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_048';
update localized_texts set RU = 'Это приятный сюрприз!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_049';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_022';
update localized_texts set RU = 'Вот.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_023';
update localized_texts set RU = 'Что? Хочешь зайти глубже в лес?!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_050';
update localized_texts set RU = 'Боишься?' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_024';
update localized_texts set RU = 'Я боюсь?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_051';
update localized_texts set RU = 'Я нет! Я просто не думал, что ты примешь такое рискованное решение.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_052';
update localized_texts set RU = 'Хорошо. А теперь поторопись.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_025';
update localized_texts set RU = 'Эй! Я просто осторожен! Там может быть опасно!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_053';
update localized_texts set RU = 'Зануда.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_026';
update localized_texts set RU = 'Я нет! Я могу быть весельчаком! Просто сейчас мне надо защищать тебя, понятно?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_054';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_027';
update localized_texts set RU = 'И вот и она...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_031';
update localized_texts set RU = 'Эй, подожди!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_056';
update localized_texts set RU = 'Жизель, я думаю, мы должны вернуться.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_057';
update localized_texts set RU = 'Больше.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_028';
update localized_texts set RU = 'Нет, правда, мы должны….' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_058';
update localized_texts set RU = '...!' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_015';
update localized_texts set RU = '{i}Д-дерьмо!{/i}' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_059';
update localized_texts set RU = '...?' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_029';
update localized_texts set RU = 'Дурак.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_030';
update localized_texts set RU = 'Две фигуры пробираются сквозь высокую траву...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_016';
update localized_texts set RU = 'Ого! Кто, черт возьми, эти парни?!' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_017';
update localized_texts set RU = 'Черт! Похоже у них недобрые намерения.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_018';
update localized_texts set RU = 'Что-то внутри меня срабатывает...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_019';
update localized_texts set RU = 'Оно говорит мне схватить Жизель и бежать отсюда.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_020';
update localized_texts set RU = 'Жизель! Мы должны уходить.... {i}сейчас же!{/i}' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_060';
update localized_texts set RU = 'Я беру ее за руку и....' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_021';
update localized_texts set RU = 'Иип!' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_031';
update localized_texts set RU = 'Н-нет! Ш-ш!!!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_061';
update localized_texts set RU = 'Что это было?!' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_001';
update localized_texts set RU = 'Она попыталась вырваться, когда я ей прикрыл рот.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_022';
update localized_texts set RU = 'Мммм! Мммм!' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_032';
update localized_texts set RU = 'Кто там?!' where TOKEN = 'GISELLEARC1SCENE2_SLIM_001';
update localized_texts set RU = 'Мы не должны им попасться!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_062';
update localized_texts set RU = 'Жизель сопротивляется, но нам удается спрятаться.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_023';
update localized_texts set RU = 'Эй, ты слышал?' where TOKEN = 'GISELLEARC1SCENE2_SLIM_002';
update localized_texts set RU = 'Да, сейчас проверю...' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_002';
update localized_texts set RU = '{i}Мммм!{/i}' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_033';
update localized_texts set RU = '{i}Бандиты! Ты должна успокоиться!{/i}' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_063';
update localized_texts set RU = 'Она продолжает паниковать. Она слишком громко дышит.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_024';
update localized_texts set RU = '{i}Жизель, пожалуйста! Они нас засекут!{/i}' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_064';
update localized_texts set RU = '{i}...!{/i}' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_034';
update localized_texts set RU = 'Достаточно. Мы должны действовать быстро!' where TOKEN = 'GISELLEARC1SCENE2_SLIM_003';
update localized_texts set RU = 'Но я не хочу, чтобы они выслеживали нас.' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_003';
update localized_texts set RU = 'Скорее всего - это какая-то птица.' where TOKEN = 'GISELLEARC1SCENE2_SLIM_004';
update localized_texts set RU = 'Эй! Это не моя вина, что теперь мы должны быть осторожны...' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_004';
update localized_texts set RU = 'Это было бы не так сложно, если бы Джим не заснул той ночью!' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_005';
update localized_texts set RU = 'Дроузеры пропали с нашим гребанным поваром…' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_006';
update localized_texts set RU = 'Эй... подожди секунду!' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_007';
update localized_texts set RU = 'Пожалуйста, пусть они пройдут мимо.... {i}Пожалуйста!{/i}' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_025';
update localized_texts set RU = 'Эй, кто там!' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_008';
update localized_texts set RU = '{i}Вот черт!{/i}' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_026';
update localized_texts set RU = '{i}...?!!{/i}' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_035';
update localized_texts set RU = '{i}Эй! Давай, выходи!{/i}' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_009';
update localized_texts set RU = 'Ха-ха! Я же говорил тебе, что это птица!' where TOKEN = 'GISELLEARC1SCENE2_SLIM_005';
update localized_texts set RU = 'Ладно. Пошли отсюда....' where TOKEN = 'GISELLEARC1SCENE2_BANDIT1_010';
update localized_texts set RU = '…' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_027';
update localized_texts set RU = 'Спасибо… Боженька!' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_028';
update localized_texts set RU = 'Фух, они ушли! Мы наконец-то...' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_065';
update localized_texts set RU = '!!' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_036';
update localized_texts set RU = 'П-подожди!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_066';
update localized_texts set RU = 'Не знал, что в ней много силы, Жизель сильно толкнула меня об дерево.' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_029';
update localized_texts set RU = 'Аххх!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_067';
update localized_texts set RU = 'Д-Да что с тобой такое?!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_068';
update localized_texts set RU = 'Ты был слишком близко!' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_037';
update localized_texts set RU = 'Пришлось! Ты хотела, чтобы тебя убили бандиты?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_069';
update localized_texts set RU = '...!' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_038';
update localized_texts set RU = 'И... Извини.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_039';
update localized_texts set RU = 'О, прекрасно. Теперь я ее напугал...' where TOKEN = 'GISELLEARC1SCENE2_NARRATION_030';
update localized_texts set RU = 'Посмотри... Все хорошо… Все отлично…' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_070';
update localized_texts set RU = 'Давай просто пойдем домой.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_071';
update localized_texts set RU = 'Согласна.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_040';
update localized_texts set RU = 'Я предупреждала вас об этом!' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_018';
update localized_texts set RU = 'Простите, мэм. Это была моя вина.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_072';
update localized_texts set RU = 'Нет, моя' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_041';
update localized_texts set RU = 'Пожалуйста, дети. Успокойтесь!' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_019';
update localized_texts set RU = '...' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_042';
update localized_texts set RU = 'И... Извините. Важно то, что вы оба в безопасности.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_020';
update localized_texts set RU = 'Жизель, поговорим позже. Тебе нужно отдохнуть.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_021';
update localized_texts set RU = 'Да. Извините меня.' where TOKEN = 'GISELLEARC1SCENE2_GISELLE_043';
update localized_texts set RU = 'Док, я ... я хотел бы, чтобы все прошло лучше. Мне {i}действительно{/i} очень жаль.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_073';
update localized_texts set RU = 'Все в порядке, {$mcName}. Достаточно того, что она находится далеко от этих бандитов…' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_022';
update localized_texts set RU = 'Видишь ли, у Жизель был уже неудачный опыт.…' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_023';
update localized_texts set RU = 'Да? А.. что случилось?' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_074';
update localized_texts set RU = 'Набег, Оруженосец... на ее дом напали.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_024';
update localized_texts set RU = 'Вот… Черт…' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_075';
update localized_texts set RU = '...? Что-то не так?' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_025';
update localized_texts set RU = 'О, н-ничего! Это просто... то же самое случилось и со мной.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_076';
update localized_texts set RU = 'Мне жаль это слышать.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_026';
update localized_texts set RU = 'Если я когда-нибудь стану рыцарем, я выгоню этих ублюдков из королевства!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_077';
update localized_texts set RU = 'Я с нетерпением буду ждать, {$mcName}.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_027';
update localized_texts set RU = 'Я еще раз благодарю вас за помощь.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_028';
update localized_texts set RU = 'Надеюсь, когда-нибудь ты станешь хорошим рыцарем.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_029';
update localized_texts set RU = 'Не сомневайтесь.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_078';
update localized_texts set RU = 'Передайте Жизель, что я надеюсь, ей скоро станет лучше.' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_079';
update localized_texts set RU = 'Не волнуйся, передам. Увидимся, Оруженосец.' where TOKEN = 'GISELLEARC1SCENE2_CECILIA_030';
update localized_texts set RU = 'Спасибо, Док!' where TOKEN = 'GISELLEARC1SCENE2_SQUIRE_080';
update localized_texts set RU = 'Черт! Чувство достоинства оруженосца на кону!' where TOKEN = 'GISELLEARC1SCENE2_QUESTION_001';
update localized_texts set RU = 'Нет!' where TOKEN = 'GISELLEARC1SCENE2_CHOICE_001';
update localized_texts set RU = 'Дело не в страхе!' where TOKEN = 'GISELLEARC1SCENE2_CHOICE_002';